#include "WorkerProfanityCommon.metalh"

kernel void workerProfanity_cusrxe(device bool* isResult [[buffer(0)]],
                                   device bool* buffResult [[buffer(1)]],
                                   constant secp256k1_ge_storage* precPtr [[buffer(2)]],
                                   constant ulong& precPitch [[buffer(3)]],
                                   constant ulong& seed_s0 [[buffer(4)]],
                                   constant ulong& seed_s1 [[buffer(5)]],
                                   constant ulong& seed_s2 [[buffer(6)]],
                                   constant ulong& seed_s3 [[buffer(7)]],
                                   constant uint& seed32 [[buffer(8)]],
                                   constant ulong& lane_start [[buffer(9)]],
                                   constant ulong& lane_count [[buffer(10)]],
                                   constant ulong& state_index_start [[buffer(11)]],
                                   constant ulong& round_start [[buffer(12)]],
                                   constant ulong& round_count [[buffer(13)]],
                                   device ProfanityWalkState* walk_state [[buffer(14)]],
                                   constant ulong& walk_state_capacity [[buffer(15)]],
                                   constant bool& use_walk_state [[buffer(16)]],
                                   constant bool& store_walk_state [[buffer(17)]],
                                   device RuntimeConfig& config [[buffer(18)]],
                                   device XorFilterState& filters [[buffer(19)]],
                                   device FilterStorageState& filter_storage [[buffer(20)]],
                                   const device uchar* bloom_storage [[buffer(21)]],
                                   const device uchar* xor_storage [[buffer(22)]],
                                   const device uchar* xor_un_storage [[buffer(23)]],
                                   const device uchar* xor_uc_storage [[buffer(24)]],
                                   const device uchar* xor_hc_storage [[buffer(25)]],
                                   device ProfanityVerifiedResult* profanity_results [[buffer(26)]],
                                   device atomic_uint* profanity_count [[buffer(27)]],
                                   uint tid [[thread_position_in_grid]]) {
    worker_profanity_impl(isResult, buffResult, precPtr, precPitch, seed_s0, seed_s1,
                          seed_s2, seed_s3, seed32, lane_start, lane_count,
                          state_index_start, round_start, round_count, walk_state,
                          walk_state_capacity, use_walk_state, store_walk_state,
                          true, true, true, true, true, true, config, filters,
                          filter_storage, bloom_storage, xor_storage, xor_un_storage,
                          xor_uc_storage, xor_hc_storage, profanity_results,
                          profanity_count, tid);
}
