#include "WorkerRecoveryPipelineCommon.metalh"

kernel void workerPvkRecoveryBatch(device bool* isResult [[buffer(0)]],
                                   device bool* buffResult [[buffer(1)]],
                                   constant secp256k1_ge_storage* precPtr [[buffer(2)]],
                                   constant ulong& precPitch [[buffer(3)]],
                                   const device char* template_text [[buffer(4)]],
                                   constant uint& template_len [[buffer(5)]],
                                   const device uchar* base_private_key [[buffer(6)]],
                                   const device int* missing_positions [[buffer(7)]],
                                   constant int& missing_count [[buffer(8)]],
                                   constant ulong& range_start [[buffer(9)]],
                                   constant ulong& range_count [[buffer(10)]],
                                   constant ulong& round [[buffer(11)]],
                                   device RuntimeConfig& config [[buffer(12)]],
                                   device XorFilterState& filters [[buffer(13)]],
                                   device FilterStorageState& filter_storage [[buffer(14)]],
                                   const device uchar* bloom_storage [[buffer(15)]],
                                   const device uchar* xor_storage [[buffer(16)]],
                                   const device uchar* xor_un_storage [[buffer(17)]],
                                   const device uchar* xor_uc_storage [[buffer(18)]],
                                   const device uchar* xor_hc_storage [[buffer(19)]],
                                   device uchar* foundPrvKeys [[buffer(20)]],
                                   device uint* foundHash160 [[buffer(21)]],
                                   device uchar* foundType [[buffer(22)]],
                                   device long* foundRound [[buffer(23)]],
                                   device atomic_uint* resultsCount [[buffer(24)]],
                                   uint tid [[thread_position_in_grid]]) {
    worker_pvk_recovery_batch_impl(isResult, buffResult, precPtr, precPitch, template_text,
                                   template_len, base_private_key, missing_positions,
                                   missing_count, range_start, range_count, round, false,
                                   config, filters, filter_storage, bloom_storage, xor_storage,
                                   xor_un_storage, xor_uc_storage, xor_hc_storage, nullptr,
                                   foundPrvKeys, foundHash160, nullptr, nullptr, foundType,
                                   nullptr, nullptr, nullptr, nullptr, foundRound, nullptr,
                                   resultsCount, tid);
}
