#include "WorkerRecoveryPipelineCommon.metalh"

kernel void workerPvkRecoverySeqVanityP2wsh(device bool* isResult [[buffer(0)]],
                                            device bool* buffResult [[buffer(1)]],
                                            constant secp256k1_ge_storage* precPtr [[buffer(2)]],
                                            constant ulong& precPitch [[buffer(3)]],
                                            const device char* template_text [[buffer(4)]],
                                            constant uint& template_len [[buffer(5)]],
                                            const device uchar* start_private_key [[buffer(6)]],
                                            constant ulong& step [[buffer(7)]],
                                            constant ulong& range_start [[buffer(8)]],
                                            constant ulong& range_count [[buffer(9)]],
                                            device RuntimeConfig& config [[buffer(10)]],
                                            device XorFilterState& filters [[buffer(11)]],
                                            device FilterStorageState& filter_storage [[buffer(12)]],
                                            const device uchar* bloom_storage [[buffer(13)]],
                                            const device uchar* xor_storage [[buffer(14)]],
                                            const device uchar* xor_un_storage [[buffer(15)]],
                                            const device uchar* xor_uc_storage [[buffer(16)]],
                                            const device uchar* xor_hc_storage [[buffer(17)]],
                                            device char* foundStrings [[buffer(18)]],
                                            device uchar* foundPrvKeys [[buffer(19)]],
                                            device uint* foundHash160 [[buffer(20)]],
                                            device uint* foundLen [[buffer(21)]],
                                            device uint* foundIter [[buffer(22)]],
                                            device uchar* foundType [[buffer(23)]],
                                            device uint* foundDerivations [[buffer(24)]],
                                            device uint* foundDerivations2 [[buffer(25)]],
                                            device char* foundPass [[buffer(26)]],
                                            device ushort* foundPassSize [[buffer(27)]],
                                            device long* foundRound [[buffer(28)]],
                                            device ulong* foundSeed [[buffer(29)]],
                                            device atomic_uint* resultsCount [[buffer(30)]],
                                            uint tid [[thread_position_in_grid]],
                                            uint stride [[threads_per_grid]]) {
    worker_pvk_recovery_seq_secp_impl(isResult, buffResult, precPtr, precPitch, template_text,
                                      template_len, start_private_key, step, range_start, range_count,
                                      config, filters, filter_storage, bloom_storage, xor_storage,
                                      xor_un_storage, xor_uc_storage, xor_hc_storage, foundStrings,
                                      foundPrvKeys, foundHash160, foundLen, foundIter, foundType,
                                      foundDerivations, foundDerivations2, foundPass, foundPassSize,
                                      foundRound, foundSeed, resultsCount, tid, stride);
}
