#include "WorkerXPCommon.metalh"

kernel void workerXP_e(device XpReplayResult* xpResults [[buffer(0)]],
                       device atomic_uint* xpCount [[buffer(1)]],
                       constant secp256k1_ge_storage* precPtr [[buffer(2)]],
                       constant ulong& precPitch [[buffer(3)]],
                       constant uchar& profile_kind [[buffer(4)]],
                       constant ulong& path_mask [[buffer(5)]],
                       constant uint& path_count [[buffer(6)]],
                       constant uint& pid_start [[buffer(7)]],
                       constant uint& pid_count [[buffer(8)]],
                       constant uint& keys_per_pid [[buffer(9)]],
                       constant ulong& linear_start [[buffer(10)]],
                       constant ulong& linear_count [[buffer(11)]],
                       constant ulong& randstorm_state_start [[buffer(12)]],
                       constant ulong& randstorm_state_count [[buffer(13)]],
                       constant uint& randstorm_time_start [[buffer(14)]],
                       constant uint& randstorm_time_count [[buffer(15)]],
                       constant uint& randstorm_delta_count [[buffer(16)]],
                       const device XpCgrStateInput* cgr_inputs [[buffer(17)]],
                       constant uint& cgr_count [[buffer(18)]],
                       const device XpSsleayInput* ssleay_inputs [[buffer(19)]],
                       constant uint& ssleay_count [[buffer(20)]],
                       constant uint& input_line_base [[buffer(21)]],
                       device RuntimeConfig& config [[buffer(22)]],
                       device XorFilterState& filters [[buffer(23)]],
                       device FilterStorageState& filterStorage [[buffer(24)]],
                       const device uchar* bloomStorage [[buffer(25)]],
                       const device uchar* xorStorage [[buffer(26)]],
                       const device uchar* xorUnStorage [[buffer(27)]],
                       const device uchar* xorUcStorage [[buffer(28)]],
                       const device uchar* xorHcStorage [[buffer(29)]],
                       constant XpRuntimeParams& xpParams [[buffer(30)]],
                       uint tid [[thread_position_in_grid]]) {
    xp_worker_impl(nullptr, nullptr, precPtr, precPitch, profile_kind, path_mask,
                   path_count, pid_start, pid_count, keys_per_pid, linear_start,
                   linear_count, randstorm_state_start, randstorm_state_count,
                   randstorm_time_start, randstorm_time_count, randstorm_delta_count,
                   cgr_inputs, cgr_count, ssleay_inputs, ssleay_count, input_line_base,
                   false, false, false, false, false, true, config, filters,
                   filterStorage, bloomStorage, xorStorage,
                   xorUnStorage, xorUcStorage, xorHcStorage,
                   xpResults, xpCount, xpParams.randstormSeedEvents,
                   xpParams.randstormScreenSeedX, xpParams.randstormScreenSeedY,
                   xpParams.randstormTimeMode, xpParams.randstormMileageStart,
                   xpParams.randstormMileageCount, tid);
}
